[project]
name = "bird-call-detection"
version = "0.1.0"
description = "Bird call detection using recordings from the Xeno-Canto API"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
